export default function Head() {
  return (
    <>
      <title>Panaverse DAO</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="Panaverse" content="Generated by Team Panaverse" />
      <link rel="icon" href="/dao.webp" />
    </>
  );
}
